package dev.springforge.engine.renderer;

import java.util.List;
import java.util.Map;

import dev.springforge.engine.model.EntityDescriptor;
import dev.springforge.engine.model.FieldDescriptor;
import dev.springforge.engine.model.GenerationConfig;
import dev.springforge.engine.model.RelationType;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generates a merged OpenAPI 3.0 specification covering all selected entities.
 * Supports YAML (default) and JSON output formats.
 */
public final class OpenApiSpecGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(OpenApiSpecGenerator.class);

    private OpenApiSpecGenerator() {}

    public static String generateYaml(List<EntityDescriptor> entities,
            GenerationConfig config) {
        var sb = new StringBuilder();
        sb.append("openapi: 3.0.3\n");
        sb.append("info:\n");
        sb.append("  title: SpringForge Generated API\n");
        sb.append("  version: 1.0.0\n");
        sb.append("  description: API specification generated by SpringForge\n");
        sb.append("paths:\n");

        for (EntityDescriptor entity : entities) {
            String basePath = "/api/v1/" + entity.classNamePlural();
            String entityName = entity.className();
            String entityNameLower = entity.classNameLower();

            appendCollectionPaths(sb, basePath, entityName, entityNameLower, entity);
            appendItemPaths(sb, basePath, entityName, entityNameLower, entity);
        }

        sb.append("components:\n");
        sb.append("  schemas:\n");

        for (EntityDescriptor entity : entities) {
            appendRequestSchema(sb, entity);
            appendResponseSchema(sb, entity);
        }

        LOG.debug("Generated OpenAPI spec for {} entities", entities.size());
        return sb.toString();
    }

    public static String generateJson(List<EntityDescriptor> entities,
            GenerationConfig config) {
        var sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"openapi\": \"3.0.3\",\n");
        sb.append("  \"info\": {\n");
        sb.append("    \"title\": \"SpringForge Generated API\",\n");
        sb.append("    \"version\": \"1.0.0\",\n");
        sb.append("    \"description\": \"API specification generated by SpringForge\"\n");
        sb.append("  },\n");
        sb.append("  \"paths\": {\n");

        for (int i = 0; i < entities.size(); i++) {
            EntityDescriptor entity = entities.get(i);
            String basePath = "/api/v1/" + entity.classNamePlural();
            String entityName = entity.className();
            boolean isLast = (i == entities.size() - 1);

            appendJsonCollectionPaths(sb, basePath, entityName, entity);
            appendJsonItemPaths(sb, basePath, entityName, entity, isLast);
        }

        sb.append("  },\n");
        sb.append("  \"components\": {\n");
        sb.append("    \"schemas\": {\n");

        for (int i = 0; i < entities.size(); i++) {
            EntityDescriptor entity = entities.get(i);
            boolean isLast = (i == entities.size() - 1);
            appendJsonRequestSchema(sb, entity, isLast);
            appendJsonResponseSchema(sb, entity, isLast);
        }

        sb.append("    }\n");
        sb.append("  }\n");
        sb.append("}\n");

        return sb.toString();
    }

    private static void appendCollectionPaths(StringBuilder sb, String basePath,
            String entityName, String entityNameLower, EntityDescriptor entity) {
        sb.append("  ").append(basePath).append(":\n");
        sb.append("    get:\n");
        sb.append("      summary: List all ").append(entityNameLower).append("s\n");
        sb.append("      operationId: getAll").append(entityName).append("s\n");
        sb.append("      tags:\n");
        sb.append("        - ").append(entityName).append("\n");
        sb.append("      parameters:\n");
        sb.append("        - name: page\n");
        sb.append("          in: query\n");
        sb.append("          schema:\n");
        sb.append("            type: integer\n");
        sb.append("            default: 0\n");
        sb.append("        - name: size\n");
        sb.append("          in: query\n");
        sb.append("          schema:\n");
        sb.append("            type: integer\n");
        sb.append("            default: 20\n");
        sb.append("      responses:\n");
        sb.append("        '200':\n");
        sb.append("          description: Paginated list of ").append(entityNameLower).append("s\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                type: object\n");
        sb.append("                properties:\n");
        sb.append("                  content:\n");
        sb.append("                    type: array\n");
        sb.append("                    items:\n");
        sb.append("                      $ref: '#/components/schemas/").append(entityName).append("ResponseDto'\n");
        sb.append("    post:\n");
        sb.append("      summary: Create a new ").append(entityNameLower).append("\n");
        sb.append("      operationId: create").append(entityName).append("\n");
        sb.append("      tags:\n");
        sb.append("        - ").append(entityName).append("\n");
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema:\n");
        sb.append("              $ref: '#/components/schemas/").append(entityName).append("RequestDto'\n");
        sb.append("      responses:\n");
        sb.append("        '201':\n");
        sb.append("          description: ").append(entityName).append(" created\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                $ref: '#/components/schemas/").append(entityName).append("ResponseDto'\n");
    }

    private static void appendItemPaths(StringBuilder sb, String basePath,
            String entityName, String entityNameLower, EntityDescriptor entity) {
        sb.append("  ").append(basePath).append("/{id}:\n");
        sb.append("    get:\n");
        sb.append("      summary: Get ").append(entityNameLower).append(" by ID\n");
        sb.append("      operationId: get").append(entityName).append("ById\n");
        sb.append("      tags:\n");
        sb.append("        - ").append(entityName).append("\n");
        sb.append("      parameters:\n");
        sb.append("        - name: id\n");
        sb.append("          in: path\n");
        sb.append("          required: true\n");
        sb.append("          schema:\n");
        sb.append("            type: ").append(javaTypeToOpenApiType(entity.idFieldType())).append("\n");
        sb.append("      responses:\n");
        sb.append("        '200':\n");
        sb.append("          description: ").append(entityName).append(" found\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                $ref: '#/components/schemas/").append(entityName).append("ResponseDto'\n");
        sb.append("        '404':\n");
        sb.append("          description: ").append(entityName).append(" not found\n");
        sb.append("    put:\n");
        sb.append("      summary: Update ").append(entityNameLower).append("\n");
        sb.append("      operationId: update").append(entityName).append("\n");
        sb.append("      tags:\n");
        sb.append("        - ").append(entityName).append("\n");
        sb.append("      parameters:\n");
        sb.append("        - name: id\n");
        sb.append("          in: path\n");
        sb.append("          required: true\n");
        sb.append("          schema:\n");
        sb.append("            type: ").append(javaTypeToOpenApiType(entity.idFieldType())).append("\n");
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema:\n");
        sb.append("              $ref: '#/components/schemas/").append(entityName).append("RequestDto'\n");
        sb.append("      responses:\n");
        sb.append("        '200':\n");
        sb.append("          description: ").append(entityName).append(" updated\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                $ref: '#/components/schemas/").append(entityName).append("ResponseDto'\n");
        sb.append("    delete:\n");
        sb.append("      summary: Delete ").append(entityNameLower).append("\n");
        sb.append("      operationId: delete").append(entityName).append("\n");
        sb.append("      tags:\n");
        sb.append("        - ").append(entityName).append("\n");
        sb.append("      parameters:\n");
        sb.append("        - name: id\n");
        sb.append("          in: path\n");
        sb.append("          required: true\n");
        sb.append("          schema:\n");
        sb.append("            type: ").append(javaTypeToOpenApiType(entity.idFieldType())).append("\n");
        sb.append("      responses:\n");
        sb.append("        '204':\n");
        sb.append("          description: ").append(entityName).append(" deleted\n");
    }

    private static void appendRequestSchema(StringBuilder sb, EntityDescriptor entity) {
        sb.append("    ").append(entity.className()).append("RequestDto:\n");
        sb.append("      type: object\n");
        sb.append("      properties:\n");
        for (FieldDescriptor field : entity.fields()) {
            if (field.isId()) continue;
            if (field.relation() != RelationType.NONE) continue;
            sb.append("        ").append(field.name()).append(":\n");
            sb.append("          type: ").append(javaTypeToOpenApiType(field.type())).append("\n");
        }
    }

    private static void appendResponseSchema(StringBuilder sb, EntityDescriptor entity) {
        sb.append("    ").append(entity.className()).append("ResponseDto:\n");
        sb.append("      type: object\n");
        sb.append("      properties:\n");
        for (FieldDescriptor field : entity.fields()) {
            if (field.relation() != RelationType.NONE) continue;
            sb.append("        ").append(field.name()).append(":\n");
            sb.append("          type: ").append(javaTypeToOpenApiType(field.type())).append("\n");
        }
    }

    private static void appendJsonCollectionPaths(StringBuilder sb, String basePath,
            String entityName, EntityDescriptor entity) {
        String lower = Character.toLowerCase(entityName.charAt(0)) + entityName.substring(1);
        sb.append("    \"").append(basePath).append("\": {\n");
        sb.append("      \"get\": {\n");
        sb.append("        \"summary\": \"List all ").append(lower).append("s\",\n");
        sb.append("        \"operationId\": \"getAll").append(entityName).append("s\",\n");
        sb.append("        \"tags\": [\"").append(entityName).append("\"],\n");
        sb.append("        \"responses\": {\n");
        sb.append("          \"200\": {\n");
        sb.append("            \"description\": \"Paginated list of ").append(lower).append("s\"\n");
        sb.append("          }\n");
        sb.append("        }\n");
        sb.append("      },\n");
        sb.append("      \"post\": {\n");
        sb.append("        \"summary\": \"Create a new ").append(lower).append("\",\n");
        sb.append("        \"operationId\": \"create").append(entityName).append("\",\n");
        sb.append("        \"tags\": [\"").append(entityName).append("\"],\n");
        sb.append("        \"responses\": {\n");
        sb.append("          \"201\": {\n");
        sb.append("            \"description\": \"").append(entityName).append(" created\"\n");
        sb.append("          }\n");
        sb.append("        }\n");
        sb.append("      }\n");
        sb.append("    },\n");
    }

    private static void appendJsonItemPaths(StringBuilder sb, String basePath,
            String entityName, EntityDescriptor entity, boolean isLastEntity) {
        String lower = Character.toLowerCase(entityName.charAt(0)) + entityName.substring(1);
        sb.append("    \"").append(basePath).append("/{id}\": {\n");
        sb.append("      \"get\": {\n");
        sb.append("        \"summary\": \"Get ").append(lower).append(" by ID\",\n");
        sb.append("        \"operationId\": \"get").append(entityName).append("ById\",\n");
        sb.append("        \"tags\": [\"").append(entityName).append("\"],\n");
        sb.append("        \"responses\": {\n");
        sb.append("          \"200\": {\n");
        sb.append("            \"description\": \"").append(entityName).append(" found\"\n");
        sb.append("          }\n");
        sb.append("        }\n");
        sb.append("      },\n");
        sb.append("      \"put\": {\n");
        sb.append("        \"summary\": \"Update ").append(lower).append("\",\n");
        sb.append("        \"operationId\": \"update").append(entityName).append("\",\n");
        sb.append("        \"tags\": [\"").append(entityName).append("\"],\n");
        sb.append("        \"responses\": {\n");
        sb.append("          \"200\": {\n");
        sb.append("            \"description\": \"").append(entityName).append(" updated\"\n");
        sb.append("          }\n");
        sb.append("        }\n");
        sb.append("      },\n");
        sb.append("      \"delete\": {\n");
        sb.append("        \"summary\": \"Delete ").append(lower).append("\",\n");
        sb.append("        \"operationId\": \"delete").append(entityName).append("\",\n");
        sb.append("        \"tags\": [\"").append(entityName).append("\"],\n");
        sb.append("        \"responses\": {\n");
        sb.append("          \"204\": {\n");
        sb.append("            \"description\": \"").append(entityName).append(" deleted\"\n");
        sb.append("          }\n");
        sb.append("        }\n");
        sb.append("      }\n");
        sb.append("    }").append(isLastEntity ? "\n" : ",\n");
    }

    private static void appendJsonRequestSchema(StringBuilder sb, EntityDescriptor entity,
            boolean isLastEntity) {
        sb.append("      \"").append(entity.className()).append("RequestDto\": {\n");
        sb.append("        \"type\": \"object\",\n");
        sb.append("        \"properties\": {\n");
        var nonIdFields = entity.fields().stream()
            .filter(f -> !f.isId() && f.relation() == RelationType.NONE)
            .toList();
        for (int i = 0; i < nonIdFields.size(); i++) {
            FieldDescriptor field = nonIdFields.get(i);
            sb.append("          \"").append(field.name()).append("\": {\n");
            sb.append("            \"type\": \"").append(javaTypeToOpenApiType(field.type())).append("\"\n");
            sb.append("          }").append(i < nonIdFields.size() - 1 ? ",\n" : "\n");
        }
        sb.append("        }\n");
        sb.append("      },\n");
    }

    private static void appendJsonResponseSchema(StringBuilder sb, EntityDescriptor entity,
            boolean isLastEntity) {
        sb.append("      \"").append(entity.className()).append("ResponseDto\": {\n");
        sb.append("        \"type\": \"object\",\n");
        sb.append("        \"properties\": {\n");
        var fields = entity.fields().stream()
            .filter(f -> f.relation() == RelationType.NONE)
            .toList();
        for (int i = 0; i < fields.size(); i++) {
            FieldDescriptor field = fields.get(i);
            sb.append("          \"").append(field.name()).append("\": {\n");
            sb.append("            \"type\": \"").append(javaTypeToOpenApiType(field.type())).append("\"\n");
            sb.append("          }").append(i < fields.size() - 1 ? ",\n" : "\n");
        }
        sb.append("        }\n");
        sb.append("      }").append(isLastEntity ? "\n" : ",\n");
    }

    private static final Map<String, String> OPENAPI_TYPE_MAP = Map.ofEntries(
        Map.entry("Long", "integer"),
        Map.entry("long", "integer"),
        Map.entry("Integer", "integer"),
        Map.entry("int", "integer"),
        Map.entry("String", "string"),
        Map.entry("Boolean", "boolean"),
        Map.entry("boolean", "boolean"),
        Map.entry("Double", "number"),
        Map.entry("double", "number"),
        Map.entry("Float", "number"),
        Map.entry("float", "number"),
        Map.entry("BigDecimal", "number"),
        Map.entry("LocalDate", "string"),
        Map.entry("LocalDateTime", "string"),
        Map.entry("Instant", "string"),
        Map.entry("UUID", "string"),
        Map.entry("byte[]", "string"),
        Map.entry("Short", "integer"),
        Map.entry("short", "integer")
    );

    private static String javaTypeToOpenApiType(String javaType) {
        return OPENAPI_TYPE_MAP.getOrDefault(javaType, "string");
    }
}
